### ISSUE TITLE
Add Repository source as part of the survey

### ISSUE THREAD

**Issue by rafaelpereyra** [mhausenblas/aws-container-security-survey-2020#4]
As a very important part of the container security can be traced back to the usage of a trusted repository of images, I would like to include the type of repository as part of the survey. 

Do you use a single source of truth for your repositories?
YES
NO

Do you consume third party approved images directly from the provider (coredns, aws-alb-ingress-controller, etc)?
YES
NO

What repository you currently use or plan to use?
Docker Hub
JFrog Repository (On Premise)
JFrog Repository (On AWS)
ECR
Other

**Comment by mhausenblas** [comment]
Addressed in #7
