### ISSUE TITLE
Suggestion: Add topic on firewall

### ISSUE THREAD

**Issue by kumo-hiyori** [mhausenblas/aws-container-security-survey-2020#8]
Would like to know if customers are putting firewall in front of their container either through: 1) At ingress only, 2) SG/Network ACL only, 3) other. If not, why not?

Also want to know common way customers do communication between container, e.g., gRPC, REST API, custom UDP based, etc.

Do customer care about east-west traffic inspection?

**Comment by mhausenblas** [comment]
Added a question to address this topic.
