### ISSUE TITLE
Monitoring tools

### ISSUE THREAD

**Issue by rafaelpereyra** [mhausenblas/aws-container-security-survey-2020#9]
I wonder if it will add value to the survey asking about monitoring solutions for the containers.

AWS offers Containers Insight but it doesn't fit all the requirements (Fargate is not supported for example).

Other options might be Prometheus, Datadog, Octant.

Even if monitoring is more a part of Ops, I belive that usage spikes could potentially indicate a security issues and might fall into Sec.

**Comment by mhausenblas** [comment]
I'd like to not overwhelm folks so I consider it out of scope for now.
